### ISSUE TITLE
Grading bar errors in Moodle

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/support#169] opened 2021-02-15 16:28 UTC
User reports seeing error in Moodle
![1dfa6ebc-a549-45b6-be63-837b50ca51be-hs_file_upload-submit-grade-error](https://user-images.githubusercontent.com/71603629/106480510-7e6fab00-6479-11eb-9fc2-4431c6ea3c56.jpg)

Have asked them to report date and time for tracking.
https://app.hubspot.com/contacts/6291320/ticket/294689362/

_Originally posted by @mattdricker in https://github.com/hypothesis/support/issues/124#issuecomment-770950140_

**Comment by mattdricker** [comment] 2021-02-15 16:30
Another Moodle user with grading error. Date and time requested.
![Screen Shot 2021-02-02 at 1 09 33 PM](https://user-images.githubusercontent.com/71603629/106625563-c576a280-6544-11eb-8fa6-e3a1d72cc0a6.png)
https://app.hubspot.com/contacts/6291320/ticket/295880016/

**Comment by mattdricker** [comment] 2021-02-15 16:31
Another report from Moodle user:
LMS URL: https://uts.fishersnet.net
LMS GUID: bab877ee339ac5453136a8969b22aea0
Date and time: Feb 2, 2021, 17:25 EST

https://app.hubspot.com/contacts/6291320/ticket/294689362/

**Comment by klemay** [comment] 2021-02-15 16:56
@mattdricker thanks for this - just to make sure I have my facts in order:

In the second ticket, we see a "Fetch grade error" - is it true that this user can save grades to the gradebook properly, even though we cannot fetch the grade?

**Comment by robertknight** [comment] 2021-04-02 12:40
@seanh [pointed out in Slack](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1617366102227800) that there are a ton of errors being logged in Sentry which may be related to this. To find them [search for `LTIOutcomesError`](https://sentry.io/organizations/hypothesis/issues/?project=259908&query=is%3Aunresolved+LTIOutcomesAPIError&statsPeriod=14d) in the lms-backend project. The LMS URL is available in the `lis_outcome_service_url` query param for each request. Unfortunately the Sentry UI doesn't provide a way to facet the individual reports. What would be useful here is to use the Sentry API to download the individual event reports and triage them locally.

**Comment by robertknight** [comment] 2021-04-08 07:44
Looking at Sentry reports one of the errors that we are seeing is "Missing or invalid consumer key or access token". After consulting the [Moodle source code](https://github.com/moodle/moodle/blob/4c26696e7e369f6e978c09a44d25e4582dedb88c/mod/lti/service.php#L56) it looks like one possible cause is that the `Authorization` header is being dropped or modified from the HTTP request that our app makes back to Moodle to report a grade. This is corroborated by an [existing Moodle issue](https://moodle.org/mod/forum/discuss.php?d=323197) from a few years ago, which features a slightly different error message that sounds like the same problem. The Moodle forum issue mentions a way to test grade feedback in LTI tools using a test tool built into Moodle.

More discussion in [this Slack thread](https://hypothes-is.slack.com/archives/C2BLQDKHA/p1617817248367100).

**Comment by LMS007** [comment] 2021-04-20 00:26
We have updated to LMS code to pass along error details back to the error dialog. In this case of this specific error (Moodle), the details will say "Missing or invalid consumer key or access token"

In that case, it's possible that a configuration of the web server may be the root cause. Specially, it may not be allowing Moodle to access the authentication headers on the grading request.

Per Rob's [link](https://moodle.org/mod/forum/discuss.php?d=323197#p1320091), the remedy, would be adjust the server config to ensure that php can read and access the authentication headers as sent by our LMS service.  Secondly, there is a third party testing tool that can verify that a server is configured and works as expected for LTI requests.

http://lti.tools/saltire/

This is probably a good starting point for debugging this problem. For example,  If a grade can be submitted using the testing tool, but not by hypothesis LMS, then that may mean something on our end is a problem.

It may be appropriate to write this up as a Q/A at https://web.hypothes.is/help-categories/moodle/ for future users that run into this issue.

**Comment by LMS007** [comment] 2021-04-20 17:29
Slack thread for reference:
https://hypothes-is.slack.com/archives/C2BLQDKHA/p1617895209380600

Closing this out for now until we know more. For the purposes of the 3 schools that came across this error (listed in that slack thread), we will continue to track those in hubspot as we are under the assumption that the fixes need to happen on their end. If anything changes we can re-open this ticket or create a new one with more details.

**Closed by LMS007** 2021-04-20 17:29 UTC
Labels: bug
